spring:
  datasource:
    url: jdbc:mariadb://10.0.17.125:3306/klol
    username: kloluser
    password: P!ssw0rd
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true


