# MariaDB의 공식 이미지 사용
FROM mariadb:10.8.2

# 환경 변수 설정 (필요에 따라 수정)
ENV MARIADB_ROOT_PASSWORD=root
ENV MARIADB_DATABASE=klol
ENV MARIADB_USER=kloluser
ENV MARIADB_PASSWORD=P!ssw0rd

# 포트 노출
EXPOSE 3306

# MariaDB 실행
CMD ["mysqld"]
